# Ednoda Capstone Day-1 Data Tour

This notebook is a beginner-friendly tour of the processed data.

What you will do:
- find the project root safely
- load the main parquet files
- inspect rows and columns
- run a few simple counts
- optionally inspect the NLP feature table

You do not need to understand every line yet. The goal is to get comfortable exploring the data.

## Before You Start

From the terminal, make sure you already ran:

```bash
source .venv/bin/activate
python scripts/build_all.py
python scripts/describe_processed_data.py
```

Optional feature table:

```bash
python scripts/enrich_sentence_features.py
```

## 1. Setup

Run this cell first. It imports the libraries and figures out where the repo root is.

In [1]:
from pathlib import Path
import json
import pandas as pd

cwd = Path.cwd()
project_root = cwd if (cwd / 'data').exists() else cwd.parent
processed = project_root / 'data' / 'processed'

print('Notebook cwd:', cwd)
print('Project root:', project_root)
print('Processed dir:', processed)

Notebook cwd: /Users/nickdewaal/ednoda-capstone-project/notebooks
Project root: /Users/nickdewaal/ednoda-capstone-project
Processed dir: /Users/nickdewaal/ednoda-capstone-project/data/processed

## 2. Check That The Processed Files Exist

This confirms that the pipeline outputs are present.

In [2]:
expected_files = [
    'sentences.parquet',
    'vocabulary_reference.parquet',
    'grammar_reference.parquet',
    'validation_summary.json',
    'build_manifest.json',
]

for name in expected_files:
    path = processed / name
    print(f'{name}:', 'FOUND' if path.exists() else 'MISSING')

sentences.parquet: FOUND
vocabulary_reference.parquet: FOUND
grammar_reference.parquet: FOUND
validation_summary.json: FOUND
build_manifest.json: FOUND

## 3. Load The Main Tables

These are the main processed tables students will work with.

In [3]:
sentences = pd.read_parquet(processed / 'sentences.parquet')
vocabulary = pd.read_parquet(processed / 'vocabulary_reference.parquet')
grammar = pd.read_parquet(processed / 'grammar_reference.parquet')

print('sentences:', len(sentences))
print('vocabulary_reference:', len(vocabulary))
print('grammar_reference:', len(grammar))

sentences: 12452
vocabulary_reference: 9935
grammar_reference: 500

## 4. Inspect The First Few Rows

`.head()` is one of the most useful commands in data work. It shows the first few rows.

In [4]:
sentences.head()

,record_id,source_dataset,source_subdataset,source_record_id,text,text_normalized,lang,granularity,cefr_level,cefr_numeric,...,grade_hint,region_hint,node_type,license_label,license_url,is_publicly_redistributable,split,analysis_json,metadata_json,created_at_utc
0,cefr_sp::CEFR-SP_Wikiauto_test::0,cefr_sp,CEFR-SP_Wikiauto_test.txt,0,2001 Heisei Ultraman Side Stories,2001 Heisei Ultraman Side Stories,en,sentence,A1,1.0,...,NaN,None,NaN,Unknown (verify upstream),None,False,test,NaN,"{""relative_file"": ""Wiki-Auto/CEFR-SP_Wikiauto_...",2026-04-09T23:20:50.220063+00:00
1,cefr_sp::CEFR-SP_Wikiauto_test::1,cefr_sp,CEFR-SP_Wikiauto_test.txt,1,1999 Special Edition bonus disc,1999 Special Edition bonus disc,en,sentence,A1,1.0,...,NaN,None,NaN,Unknown (verify upstream),None,False,test,NaN,"{""relative_file"": ""Wiki-Auto/CEFR-SP_Wikiauto_...",2026-04-09T23:20:50.220063+00:00
2,cefr_sp::CEFR-SP_Wikiauto_test::2,cefr_sp,CEFR-SP_Wikiauto_test.txt,2,"Sucre was killed on June 4 , 1830 .","Sucre was killed on June 4 , 1830 .",en,sentence,A1,1.0,...,NaN,None,NaN,Unknown (verify upstream),None,False,test,NaN,"{""relative_file"": ""Wiki-Auto/CEFR-SP_Wikiauto_...",2026-04-09T23:20:50.220063+00:00
3,cefr_sp::CEFR-SP_Wikiauto_test::3,cefr_sp,CEFR-SP_Wikiauto_test.txt,3,There are four games in the series,There are four games in the series,en,sentence,A1,1.0,...,NaN,None,NaN,Unknown (verify upstream),None,False,test,NaN,"{""relative_file"": ""Wiki-Auto/CEFR-SP_Wikiauto_...",2026-04-09T23:20:50.220063+00:00
4,cefr_sp::CEFR-SP_Wikiauto_test::4,cefr_sp,CEFR-SP_Wikiauto_test.txt,4,The international yard is exactly 0.9144 metres .,The international yard is exactly 0.9144 metres .,en,sentence,A2,2.0,...,NaN,None,NaN,Unknown (verify upstream),None,False,test,NaN,"{""relative_file"": ""Wiki-Auto/CEFR-SP_Wikiauto_...",2026-04-09T23:20:50.220063+00:00

In [5]:
vocabulary.head()

,record_id,source_dataset,source_record_id,headword,lemma,surface_form,pos,cefr_level,cefr_numeric,list_name,license_label,license_url,metadata_json,created_at_utc
0,cefrj_vocab::cefrj_vocabulary_profile::0,cefrj,0,a,a,a,determiner,A1,1,cefrj_vocabulary_profile,CEFR-J terms (verify),None,"{""raw"": {""core_inventory_1"": null, ""core_inven...",2026-04-09T23:20:53.718691+00:00
1,cefrj_vocab::cefrj_vocabulary_profile::1,cefrj,1,a.m./A.M./am/AM,a.m./A.M./am/AM,a.m./A.M./am/AM,adverb,A1,1,cefrj_vocabulary_profile,CEFR-J terms (verify),None,"{""raw"": {""core_inventory_1"": null, ""core_inven...",2026-04-09T23:20:53.718691+00:00
2,cefrj_vocab::cefrj_vocabulary_profile::2,cefrj,2,abandon,abandon,abandon,verb,B1,3,cefrj_vocabulary_profile,CEFR-J terms (verify),None,"{""raw"": {""core_inventory_1"": null, ""core_inven...",2026-04-09T23:20:53.718691+00:00
3,cefrj_vocab::cefrj_vocabulary_profile::3,cefrj,3,abandoned,abandoned,abandoned,adjective,B2,4,cefrj_vocabulary_profile,CEFR-J terms (verify),None,"{""raw"": {""core_inventory_1"": null, ""core_inven...",2026-04-09T23:20:53.718691+00:00
4,cefrj_vocab::cefrj_vocabulary_profile::4,cefrj,4,ability,ability,ability,noun,A2,2,cefrj_vocabulary_profile,CEFR-J terms (verify),None,"{""raw"": {""core_inventory_1"": null, ""core_inven...",2026-04-09T23:20:53.718691+00:00

In [6]:
grammar.head()

,record_id,source_dataset,source_record_id,grammar_item,grammar_description,cefr_level,cefr_numeric,framework,tags_json,examples_json,license_label,license_url,metadata_json,created_at_utc
0,cefrj_grammar::0,cefrj,1,I am,AFF. DEC.,A1,1.0,CEFR-J,"[""PP.I_am"", ""AFF. DEC.""]","[""I am""]",CEFR-J terms (verify),None,"{""raw"": {""cefr_j_level_raw"": ""A1.1"", ""freq_dis...",2026-04-09T23:20:59.358411+00:00
1,cefrj_grammar::1,cefrj,1-1,I am not,NEG. DEC.,A1,1.0,CEFR-J,"[""PP.I_am_not"", ""NEG. DEC.""]","[""I am not""]",CEFR-J terms (verify),None,"{""raw"": {""cefr_j_level_raw"": ""A1.1"", ""freq_dis...",2026-04-09T23:20:59.358411+00:00
2,cefrj_grammar::2,cefrj,1-2,Am I ...?,AFF. INT.,NaN,NaN,CEFR-J,"[""PP.am_I"", ""AFF. INT.""]","[""Am I ...?""]",CEFR-J terms (verify),None,"{""raw"": {""cefr_j_level_raw"": null, ""freq_disp""...",2026-04-09T23:20:59.358411+00:00
3,cefrj_grammar::3,cefrj,1-3,Am I not ...?,NEG. INT.,NaN,NaN,CEFR-J,"[""PP.am_I_not"", ""NEG. INT.""]","[""Am I not ...?""]",CEFR-J terms (verify),None,"{""raw"": {""cefr_j_level_raw"": null, ""freq_disp""...",2026-04-09T23:20:59.358411+00:00
4,cefrj_grammar::4,cefrj,2,You are,AFF. DEC.,B1,3.0,CEFR-J,"[""PP.you_are"", ""AFF. DEC.""]","[""You are""]",CEFR-J terms (verify),None,"{""raw"": {""cefr_j_level_raw"": ""B1.1"", ""freq_dis...",2026-04-09T23:20:59.358411+00:00

## 5. See The Columns

A dataframe column is like a field in a spreadsheet table.

In [7]:
sentences.columns.tolist()

['record_id',
 'source_dataset',
 'source_subdataset',
 'source_record_id',
 'text',
 'text_normalized',
 'lang',
 'granularity',
 'cefr_level',
 'cefr_numeric',
 'difficulty_source',
 'topic_hint',
 'grammar_hint',
 'grade_hint',
 'region_hint',
 'node_type',
 'license_label',
 'license_url',
 'is_publicly_redistributable',
 'split',
 'analysis_json',
 'metadata_json',
 'created_at_utc']

In [8]:
vocabulary.columns.tolist()

['record_id',
 'source_dataset',
 'source_record_id',
 'headword',
 'lemma',
 'surface_form',
 'pos',
 'cefr_level',
 'cefr_numeric',
 'list_name',
 'license_label',
 'license_url',
 'metadata_json',
 'created_at_utc']

## 6. Basic Counts

This is a very common first step in ML and NLP work: count what you have.

In [9]:
sentences['cefr_level'].value_counts(dropna=False)

cefr_level
B2     3330
B1     3305
NaN    2448
C1     1744
A2     1271
C2      230
A1      124
Name: count, dtype: int64

In [10]:
sentences['split'].value_counts(dropna=False)

split
train         7178
NaN           2448
test          1460
validation    1366
Name: count, dtype: int64

In [11]:
sentences['source_subdataset'].value_counts(dropna=False)

source_subdataset
CEFR-SP_Wikiauto_train.txt     5990
ednoda_snapshot_cleaned.csv    2448
CEFR-SP_SCoRE_train.txt        1188
CEFR-SP_Wikiauto_test.txt       762
CEFR-SP_Wikiauto_dev.txt        701
CEFR-SP_SCoRE_test.txt          698
CEFR-SP_SCoRE_dev.txt           665
Name: count, dtype: int64

## 7. Select Only A Few Useful Columns

This is a common pattern: choose a few columns, then preview them.

In [12]:
sentences[[
    'text_normalized',
    'cefr_level',
    'source_subdataset',
    'split',
]].head(15)

,text_normalized,cefr_level,source_subdataset,split
0,2001 Heisei Ultraman Side Stories,A1,CEFR-SP_Wikiauto_test.txt,test
1,1999 Special Edition bonus disc,A1,CEFR-SP_Wikiauto_test.txt,test
2,"Sucre was killed on June 4 , 1830 .",A1,CEFR-SP_Wikiauto_test.txt,test
3,There are four games in the series,A1,CEFR-SP_Wikiauto_test.txt,test
4,The international yard is exactly 0.9144 metres .,A2,CEFR-SP_Wikiauto_test.txt,test
5,Magic is common in the game .,A2,CEFR-SP_Wikiauto_test.txt,test
6,The pass is open only from May to November .,A2,CEFR-SP_Wikiauto_test.txt,test
7,Research on the Aha !,A2,CEFR-SP_Wikiauto_test.txt,test
8,The ratio of height to width is 5 to 8 .,A2,CEFR-SP_Wikiauto_test.txt,test
9,3 ... Bf5 is most often played .,A2,CEFR-SP_Wikiauto_test.txt,test
10,Exchange students from Italy and Germany help ...,A2,CEFR-SP_Wikiauto_test.txt,test
11,"In 2010 , the band played in more than 150 con...",A2,CEFR-SP_Wikiauto_test.txt,test
12,"After one year , she opened the bookshop again .",A2,CEFR-SP_Wikiauto_test.txt,test
13,Ramen comes in various shapes and lengths .,A2,CEFR-SP_Wikiauto_test.txt,test
14,The mall opened its doors to the public August...,A2,CEFR-SP_Wikiauto_test.txt,test

## 8. Filter Rows

Here we keep only A1 sentences.

In [13]:
a1_sentences = sentences[sentences['cefr_level'] == 'A1']
a1_sentences[['text_normalized', 'cefr_level']].head(15)

                                        text_normalized cefr_level
0                     2001 Heisei Ultraman Side Stories         A1
1                       1999 Special Edition bonus disc         A1
2                   Sucre was killed on June 4 , 1830 .         A1
3                    There are four games in the series         A1
762   There are three main types of chocolate : whit...         A1
763                He died on 6 October 1837 in Paris .         A1
764               Nobbs died on 8 August 2015 aged 80 .         A1
765    McAlpine died on 4 March 2018 at the age of 81 .         A1
766      Ullsten died on 28 May 2018 at the age of 86 .         A1
767   Glucksmann died in Paris on 10 November 2015 a...         A1
1463  Delpire died in Paris on 26 September 2017 in ...         A1
1464     Harris died on 9 May 2019 , at the age of 93 .         A1
1465  Long died on January 15 , 2017 , at the age of...         A1
1466                        Matos died on 8 June 2019 .         A1
1467     Pazos died on 24 May 2019 , at the age of 89 .         A1

## 9. Read The Validation Summary

This tells you whether the processed tables passed validation.

In [14]:
validation_summary = json.loads((processed / 'validation_summary.json').read_text())
validation_summary['hard_failures']

[]

## 10. Optional: Load Sentence Features

If you already ran `python scripts/enrich_sentence_features.py`, you can load the NLP feature table.

In [15]:
sentence_features_path = processed / 'sentence_features.parquet'
print('sentence_features exists:', sentence_features_path.exists())

sentence_features = pd.read_parquet(sentence_features_path) if sentence_features_path.exists() else None

sentence_features exists: True

In [16]:
if sentence_features is not None:
    sentence_features[[
        'text_normalized',
        'cefr_level',
        'surface_token_count',
        'lexical_density',
        'noun_count',
        'verb_count',
        'readability_flesch_reading_ease',
        'root_token',
        'root_pos',
    ]].head(15)
else:
    print('Run this in the terminal first: python scripts/enrich_sentence_features.py')

## 11. Simple Feature Analysis

A very normal ML question is: do some features vary by CEFR level?

Below we compare average lexical density by CEFR level.

In [17]:
if sentence_features is not None:
    sentence_features.groupby('cefr_level')['lexical_density'].mean().sort_index()
else:
    print('Run this in the terminal first: python scripts/enrich_sentence_features.py')

## 12. Good Next Questions

Beginner-friendly questions students could explore next:
- Which CEFR levels are most common in the sentence pool?
- Are `Wiki-Auto` and `SCoRE` different in sentence length or lexical density?
- Does lexical density rise as CEFR level rises?
- Which CEFR-J vocabulary words seem most useful for difficulty baselines?
- Which CEFR-J grammar entries could become interpretable grammar tags?

In [18]:
# Create a view of just the Ednoda nodes
ednoda_rows = sentences[sentences['source_dataset'] == 'ednoda_snapshot']

print(f"I found {len(ednoda_rows)} Ednoda nodes!")

# Show the first 10 rows with the grades and analysis columns
ednoda_rows[['text', 'node_type', 'grade_hint', 'analysis_json']].head(10)

I found 2448 Ednoda nodes!

,text,node_type,grade_hint,analysis_json
10004,I’m from Canada.,expression,five,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t..."
10005,I’m from India.,expression,five,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t..."
10006,I’m from Korea.,expression,five,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t..."
10007,I’m from Vietnam.,expression,five,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t..."
10008,I’m from the U.S.,expression,five,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t..."
10009,I’m from France.,expression,five,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t..."
10010,My name is Tom.,expression,five,"{""tokens"": [{""dep"": ""poss"", ""pos"": ""PRON"", ""ta..."
10011,My name is Mohan.,expression,five,"{""tokens"": [{""dep"": ""poss"", ""pos"": ""PRON"", ""ta..."
10012,My name is Linh.,expression,five,"{""tokens"": [{""dep"": ""poss"", ""pos"": ""PRON"", ""ta..."
10013,My name is Mia.,expression,five,"{""tokens"": [{""dep"": ""poss"", ""pos"": ""PRON"", ""ta..."

In [19]:
ednoda_rows.iloc[0:1].T

                                                                         10004
record_id                                                ednoda_snapshot::1950
source_dataset                                                 ednoda_snapshot
source_subdataset                                  ednoda_snapshot_cleaned.csv
source_record_id                                                          1950
text                                                          I’m from Canada.
text_normalized                                               I’m from Canada.
lang                                                                        en
granularity                                                         expression
cefr_level                                                                 NaN
cefr_numeric                                                               NaN
difficulty_source                                                     internal
topic_hint                                                                None
grammar_hint                                                              None
grade_hint                                                                five
region_hint                                                               None
node_type                                                           expression
license_label                                                 Internal/Private
license_url                                                               None
is_publicly_redistributable                                              False
split                                                                      NaN
analysis_json                {"tokens": [{"dep": "nsubj", "pos": "PRON", "t...
metadata_json                {"raw": {"education_node_id": "1950", "text": ...
created_at_utc                                2026-04-09T23:21:00.740481+00:00

In [20]:
pd.set_option('display.max_columns', None)
ednoda_rows.head(5)

,record_id,source_dataset,source_subdataset,source_record_id,text,text_normalized,lang,granularity,cefr_level,cefr_numeric,difficulty_source,topic_hint,grammar_hint,grade_hint,region_hint,node_type,license_label,license_url,is_publicly_redistributable,split,analysis_json,metadata_json,created_at_utc
10004,ednoda_snapshot::1950,ednoda_snapshot,ednoda_snapshot_cleaned.csv,1950,I’m from Canada.,I’m from Canada.,en,expression,NaN,NaN,internal,None,None,five,None,expression,Internal/Private,None,False,NaN,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t...","{""raw"": {""education_node_id"": ""1950"", ""text"": ...",2026-04-09T23:21:00.740481+00:00
10005,ednoda_snapshot::1951,ednoda_snapshot,ednoda_snapshot_cleaned.csv,1951,I’m from India.,I’m from India.,en,expression,NaN,NaN,internal,None,None,five,None,expression,Internal/Private,None,False,NaN,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t...","{""raw"": {""education_node_id"": ""1951"", ""text"": ...",2026-04-09T23:21:00.740481+00:00
10006,ednoda_snapshot::1952,ednoda_snapshot,ednoda_snapshot_cleaned.csv,1952,I’m from Korea.,I’m from Korea.,en,expression,NaN,NaN,internal,None,None,five,None,expression,Internal/Private,None,False,NaN,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t...","{""raw"": {""education_node_id"": ""1952"", ""text"": ...",2026-04-09T23:21:00.740481+00:00
10007,ednoda_snapshot::1953,ednoda_snapshot,ednoda_snapshot_cleaned.csv,1953,I’m from Vietnam.,I’m from Vietnam.,en,expression,NaN,NaN,internal,None,None,five,None,expression,Internal/Private,None,False,NaN,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t...","{""raw"": {""education_node_id"": ""1953"", ""text"": ...",2026-04-09T23:21:00.740481+00:00
10008,ednoda_snapshot::1954,ednoda_snapshot,ednoda_snapshot_cleaned.csv,1954,I’m from the U.S.,I’m from the U.S.,en,expression,NaN,NaN,internal,None,None,five,None,expression,Internal/Private,None,False,NaN,"{""tokens"": [{""dep"": ""nsubj"", ""pos"": ""PRON"", ""t...","{""raw"": {""education_node_id"": ""1954"", ""text"": ...",2026-04-09T23:21:00.740481+00:00